# Generated by Django 4.2.4 on 2023-09-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_author_fullname'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quote',
            name='quote for username',
        ),
    ]
