# Generated by Django 4.2.4 on 2023-09-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_tag_remove_author_user_remove_quote_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born_date',
            field=models.DateField(default='01/01/1900'),
        ),
    ]
