# Generated by Django 4.2.4 on 2023-09-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_alter_author_born_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='quote',
            name='tags',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
