# Generated by Django 4.2.4 on 2023-09-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_remove_quote_tags_delete_tag_quote_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born_date',
            field=models.CharField(default='01/01/1900'),
        ),
    ]
