# Generated by Django 4.2.4 on 2023-09-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_alter_author_born_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born_location',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='fullname',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tags',
            field=models.CharField(null=True),
        ),
    ]
